micronaut:
  application:
    name: oda-twitch-service
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
twitch:
  client:
    id: ${TWITCH_CLIENT_ID}
    secret: ${TWITCH_CLIENT_SECRET}
flyway:
  datasources:
    default:
      enabled: true
      schemas: 'twitch'
      default-schema: 'twitch'
endpoints:
  prometheus:
    sensitive: false
  metrics:
    sensitive: false
datasources:
  default:
    schema: 'twitch'
